import Head from 'next/head'
import { Col, Container, Row } from 'react-bootstrap'
import { useState } from 'react'
import UsersCard from '@/Components/UsersCard/UsersCard'
import Image from 'next/image'

export default function Home(props) {
  const [loading, setLoading] = useState(true)
  const allUsers = props.data;
  const [userDetails, setUserDetails] = useState();
  const [index, setIndex] = useState();
  const active = {
    index,
    setIndex
  }

  const myLoader = () => {
    return `${userDetails?.avatar}`;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>
          <Container>
            <Row className='py-1 py-lg-5 g-1 g-lg-4'>
              <Col lg={6} className='order-2 order-lg-1'>
                <div className='border rounded p-3 pb-4 shadow-colored'>
                  <h2 className='text-center heading'>User List</h2>
                  <div
                    style={{ maxHeight: '78vh', overflowY: 'scroll' }}
                    className='p-3'>

                    {/* {
                      loading === true && <Loader />
                    }
*/}
                    {
                      allUsers?.length === 0 && <p>No data found</p>
                    }

                    {
                      allUsers?.sort((a, b) => {
                        if (a.profile.firstName < b.profile.firstName) {
                          return -1;
                        }
                        else return 1;
                      }).map((user, i) => <UsersCard key={i} i={i} active={active} user={user} setUserDetails={setUserDetails} />)
                    }

                  </div>
                </div>
              </Col>
              <Col lg={6} className='order-1 order-lg-2'>
                <div className='border rounded shadow-colored p-3 h-100'>
                  <h2 className='text-center heading'>User Details</h2>

                  <div className="text-center py-0 py-lg-3">
                    <div className='image-wrapper'>
                      <Image loader={myLoader} src={`${userDetails?.avatar}`} width={50}
                        height={50} alt="po" className="rounded-circle" />
                    </div>
                  </div>
                  {
                    userDetails?.profile?.username ?
                      <p className='pt-2 text-center'>@{userDetails?.profile?.username}</p>
                      :
                      <p className='pt-2 text-center'>username</p>
                  }
                  <div className="mb-1 mb-lg-3">
                    <textarea defaultValue={userDetails?.Bio} className='form-control' disabled></textarea>
                  </div>
                  <div className="mb-1 mb-lg-3">
                    <label htmlFor="">Full Name</label>

                    <input type="text" defaultValue={userDetails ? `${userDetails?.profile?.firstName} ${userDetails?.profile?.lastName}` : ''} className='form-control' disabled />

                  </div>
                  <div className="mb-1 mb-lg-3">
                    <label htmlFor="">Job Title</label>
                    <input type="text" defaultValue={userDetails?.jobTitle} className='form-control' disabled />
                  </div>
                  <div className="mb-1 mb-lg-3">
                    <label htmlFor="">Email</label>
                    <input type="text" defaultValue={userDetails?.profile?.email} className='form-control' disabled />
                  </div>
                </div>
              </Col>
            </Row>
          </Container>
        </div >
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://602e7c2c4410730017c50b9d.mockapi.io/users');
  const data = await res.json();

  return {
    props: {
      data,
    },
  }
}
